# Generated by Django 5.0.4 on 2024-04-09 15:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='students',
        ),
        migrations.AddField(
            model_name='instructor',
            name='rating',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='student',
            name='level',
            field=models.CharField(choices=[('B', 'Beginner'), ('I', 'Intermediate'), ('A', 'Advanced'), ('P', 'Pro')], default=('B', 'Beginner')),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='age',
            field=models.IntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(110)]),
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('level', models.CharField(choices=[('B', 'Beginner'), ('I', 'Intermediate'), ('A', 'Advanced'), ('P', 'Pro')], default=('B', 'Beginner'))),
                ('location', models.CharField(choices=[('B', 'Beginners Bay'), ('S', 'Santana'), ('P', 'Popoyo')])),
                ('instructor', models.ManyToManyField(to='main_app.instructor')),
                ('student', models.ManyToManyField(to='main_app.student')),
            ],
            options={
                'ordering': ['time'],
            },
        ),
    ]
