# Generated by Django 5.0.4 on 2024-04-11 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_student_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='email',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='instructor',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.student'),
            preserve_default=False,
        ),
    ]
