# Generated by Django 5.0.4 on 2024-04-11 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_instructor_email_instructor_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='email',
            field=models.CharField(default='example@mail.com'),
        ),
    ]
