# Generated by Django 5.0.4 on 2024-04-11 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_instructor_email_alter_student_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='email',
            field=models.CharField(default='example@mail.com'),
        ),
    ]
