# Generated by Django 5.0.4 on 2024-04-15 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
